name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p /home/deploy/.ssh
        echo "$SSH_PRIVATE_KEY" > /home/deploy/.ssh/id_rsa
        chmod 600 /home/deploy/.ssh/id_rsa
        ssh -i /home/deploy/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@prophesierc.site << 'EOF'
        cd /var/www/prophesierc.site/prophesierc/
        git pull origin main
        sudo systemctl restart nginx
        EOF


