name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add a debugging step to print environment variables
      - name: Debug GitHub Actions Environment
        run: |
          env | sort

      # Print contents of the target directory on the remote server
      - name: List Remote Directory
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} deploy@prophesierc.site ls -la /var/www/prophesierc.site/prophesierc/contact-form

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          source: "." 
          target: "/var/www/prophesierc.site/prophesierc/contact-form"
          host: prophesierc.site
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
