name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: |
          sudo apt update
          sudo apt install openssh-client

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: prophesierc.site
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "prophesierc"
          target: "/var/www/prophesierc.site/prophesierc/"  
          strip-components: 1
          port: 22
