name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
  - name: Debug SSH Key
    run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
  - name: Copy files to server
    uses: appleboy/scp-action@master
    with:
      source: "."
      target: "/var/www/prophesierc.site/prophesierc/contact-form"
      host: prophesierc.site
      username: deploy
      key: ${{ secrets.SSH_PRIVATE_KEY }}
